apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    node.type: es-node-master
  name: es
spec:
  replicas: 1
  selector:
    matchLabels:
      node.type: es-node-master
  template:
    metadata:
      labels:
        node.type: es-node-master
    spec:
      containers:
        - name: es-node-master-container
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"
            - name: ELASTIC_PASSWORD
              value: "Toan123456789"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          readinessProbe:
            exec:
              command:
              - curl
              - -u
              - -k
              - elastic:Toan123456789
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - curl
              - -k
              - -u
              - elastic:Toan123456789
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 9200
            - containerPort: 9300

---

apiVersion: v1
kind: Service
metadata:
  labels:
    es.service: es-service
  name: es-service
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    node.type: es-node-master
